### PR TITLE
Add ONX (Onixcoin)

### PR DESCRIPTION
**Pull request by jestevez**
Hi, please add Onicoin

regards

### CODE REVIEW

**Comment by iancoleman** [comment]
Regarding the line `setHdCoin(99);`

Onixcoin doesn't seem to be listed in BIP44 - https://github.com/satoshilabs/slips/blob/master/slip-0044.md

Is there a reason why it's using 99 here (which is registered to 'SaveTheOcean' coin)?

**Comment by jestevez** [comment]
Hi @iancoleman 

Apparently 99 is correct value .

I tried to contact the ONIX developers to clarify this value. 

I've tried this derivation and compared the official android wallet that uses BIP44

The result is that it generates the correct addresses But the xpub and xpriv not

Thank you for your observation, when I have the official values ​​I tell you.

**Comment by mikeyb** [comment]
IMO ONIX needs to resolve their bip44 namespace conflict either through accepted PR to change decimal 99 in slip44, or pick an unused namespace. This is just sloppy. I would not merge this until conflict is resolved or you may mistankingly generate addresses under the wrong namespace if this changes in the future.

**Comment by mikeyb** [comment]
@jestevez 99 is NOT the correct value.  The correct value would be listed on slip44 page.  That is the source of truth.  Not what someone lazily slaps in a wallet.  Just because they program their wallet to use 99 does not mean it is correct.  They are in the very least noobs, and that mistake alone is enough to tell me they have no idea what they are doing and you should avoid investments in such sloppy amateur networks.

**Comment by jestevez** [comment]
Hi @mikeyb Your right the 99 is not a correct value, but I was using it in your wallet. I have already opened an issue to change them to a correct value

**Comment by jestevez** [comment]
Hi @iancoleman The correct code 174 has already been added although with 3 commits apologies for my error

**Pull request merged**
