### PR TITLE
Add CPUchain support

### PR DESCRIPTION
**Pull request by minkcrypto**

### CODE REVIEW

**Comment by iancoleman** [comment]
Thanks, looks good. Should this have an entry in bitcoinjs-extensions.js or is it a segwit-only coin?

**Comment by minkcrypto** [comment]
@iancoleman We use both segwith and legacy address, should I do something more?

**Comment by minkcrypto** [comment]
@iancoleman Done!

**Comment by iancoleman** [comment]
The test is failing for me, do you know how the value used in this PR was obtained and is it correct?

**Comment by minkcrypto** [comment]
@iancoleman See our chain spec https://github.com/cpuchain/cpuchain/blob/master/src/chainparams.cpp

**Pull request merged**
