### PR TITLE
Added support for Blocknode

### PR DESCRIPTION
**Pull request by CCob**
Add support for Blocknode

### CODE REVIEW

**Comment by iancoleman** [comment]
Look good. Any particular reason for using "tBND"? No other testnets in this tool have this sort of notation.

**Comment by CCob** [comment]
Mainly consistency with the Blocknode wallet, which shows tBND when running on testnet.  See bottom right of the wallet.

bnd

No worries if you'd like to keep consistency though, so happy to change it if you want.

**Comment by CCob** [comment]
Hi Ian,  An update on this one.  Are you happy to merge or should I change tBND to something else?

**Comment by CCob** [comment]
Thank you Ian

**Pull request merged**
