### PR TITLE
Fix incorrect address generation for altcoins with BIP38 enabled

### PR DESCRIPTION
**Pull request by woodser**
This PR fixes a bug which causes addresses to be incorrect for altcoins when BIP38 is enabled.

### CODE REVIEW

**Comment by woodser** [comment]
Added fix for zcash by increasing maximum payload length to 22.

**Comment by iancoleman** [comment]
Thanks, this is great.

I'll add a test for zcash BIP38 generation to ensure no future regression.

Regarding the change to bitcoinjs-3.3.2.js

This code is never executed by this tool so I'd prefer to leave it unchanged, especially since this change is to a library that I do not maintain myself. Changes make it difficult to upgrade the tool in the future.

To put it another way, there's no way to test that particular change using the current test setup (selenium) so the change should not be included as there's no way to detect breakage in the future.

Please revert the change to bitcoinjs before this is merged.

Thanks again for the pull request.

**Comment by woodser** [comment]
Great, I reverted the max payload length fix for zcash.  Thanks.

**Comment by woodser** [comment]
FYI I submitted changes from your branch to bitcoinjs-lib to support Zcash: https://github.com/bitcoinjs/bitcoinjs-lib/pull/1078

**Pull request merged**
