### PR TITLE
fixed signing message for DigiByte

### PR DESCRIPTION
**Pull request by mctrivia**
Not fixed by this pull request because I could not figure out where it is done but like Bitcoin BIP44,BIP49,BIP84 should be xpub,ypub,zpub respectively.

### CODE REVIEW

**Comment by iancoleman** [comment]
xpub,ypub,zpub are determined by the presence of `bip32.public` and `bip32.private` values in segwit-parameters.js

eg ypub is set by values in

`bitcoinjs.bitcoin.networks.bitcoin.p2wpkhInP2sh.bip32`

and zpub is set by values in

`bitcoinjs.bitcoin.networks.bitcoin.p2wpkh.bip32`

more info

http://docs.electrum.org/en/latest/xpub_version_bytes.html

**Comment by mctrivia** [comment]
thanks.  have amended pull request to included fixs to bip49, and 84 prefixs

**Comment by johnnynanjiang** [comment]
Is it ok to merge this PR so that we can continue with our testing? Thanks.

**Comment by mctrivia** [comment]
yep it now returns correct values and though signing message is not used anywhere i can find now has correct value for those looking to work with the coin.

**Comment by iancoleman** [comment]
Thanks for this and apologies for the delay! I appreciate it.

**Comment by johnnynanjiang** [comment]
> Thanks for this and apologies for the delay! I appreciate it.

Hi @iancoleman, when would the page be updated?

**Comment by iancoleman** [comment]
Should be updated this week, just waiting to see if I can fit in some other PRs before deploying.

**Comment by mctrivia** [comment]
looks like iancoleman.io still not updated
unless my phone is just caching and refusing to refresh

**Comment by iancoleman** [comment]
Yeah sorry still not updated... my bad, been mad busy lately. It's still sitting in my todo list so don't worry I haven't forgotten.

**Comment by iancoleman** [comment]
Just put out a new release. Thanks for the pushes and reminders :)

**Pull request merged**
