### PR TITLE
feat: rsk network

### PR DESCRIPTION
**Pull request by bguiz**
## What

- Added a conditional check for `isRsk` mirroring the `isEthereum` implementation
- Added an implementation of an EIP-1191 compliant address checksum calculator in function `toChecksumAddressForRsk`

## Why

- Need to generate addresses with checksums using the correct `chainId`, as per EIPs:
  - [EIP-1191](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1191.md), and
  - [EIP-155](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-155.md), and
  - [EIP-55](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-55.md)

## Refs

- Verify generated addresses using [RSK address valiator](https://address-validator.rsk.co/)
- [Specifications](https://developers.rsk.co/rsk/architecture/account-based/)

### CODE REVIEW

**Comment by bguiz** [comment]
@iancoleman bump ^

**Comment by iancoleman** [comment]
Look good thanks. What happened to rubycoin? I appreciate tidying up the naming regardless of what happened, but I couldn't understand why it changed from `libs.bitcoin.networks.rubycoin`

**Comment by bguiz** [comment]
> What happened to rubycoin? I appreciate tidying up the naming regardless of what happened, but I couldn't understand why it changed from `libs.bitcoin.networks.rubycoin`

@iancoleman This is the PR in which the reference to rubycoin reference was added: https://github.com/iancoleman/bip39/pull/396/files

RSK isn't related to rubycoin, and that was an error. Copying @ilanolkies 

This one fixes it by defining its own networks, as per the specifications here:
https://developers.rsk.co/rsk/architecture/account-based/
I've added this link to the PR description.

**Comment by ilanolkies** [comment]
It was my mistake setting rubycoin. Actually this updates fix the problem

**Comment by bguiz** [comment]
Thanks @iancoleman!

**Pull request merged**
