### PR TITLE
Added BST - BlockStamp

### PR DESCRIPTION
**Pull request by skironDotNet**

### CODE REVIEW

**Comment by iancoleman** [comment]
Why is deimos removed in segwit parameters? This PR is for blockstamp.

**Comment by skironDotNet** [comment]
Because deimos word didn't appear anywhere in the source code, no reference to it, and was crushing code execution when put my code under those lines, 

deimos

**but since I put BST code above deimos we can un-commentthat code. 
Would you like me to un-comment deimos?**

**Comment by iancoleman** [comment]
Yes please uncomment Deimos for this PR, that part of the code will be investigated in #297.

Thanks for reporting it, this is very unusual both to have unused code and for it to be causing problems. If you have any further details or description please feel free to add it to #297.

**Comment by skironDotNet** [comment]
I still believe you could merge with deimos commended out but deimos resorted, and re: "this is very unusual both to have unused code"  it could get there by mistake of someone, or bad merge.... 
"and for it to be causing problems"... I'll answer why in #297 as advised. Thanks!

**Pull request merged**
