### PR TITLE
Added Split Phrase Card Output

### PR DESCRIPTION
**Pull request by mctrivia**
Seed phrases are a great way to backup but if someone finds where you wrote them down you could lose everything.  My suggestion is to store seed phrase on 3 cards where 2 of 3 cards are needed to recover.  This way if one is lost you can still recover, and if a 3rd party finds 1 there is still 10n/3 bits of missing data for them to guess(n is number of words in seed).  At 24 word seed phrase this makes 80bits missing which is still years to brute force.

### CODE REVIEW

**Comment by mctrivia** [comment]
yah i thought about doing a more complicated system.  but this is likely to be used by my kids after I die and this is super easy for anyone and still secure.

**Comment by cernekee** [comment]
Using SSSS is pretty easy -- worst part is that it requires a separate tool.  You just convert to hex, split, then convert each share back to mnemonics.  And you don't lose any security at all, because one share is useless on its own.

I thought about integrating it into the bip39 page but the UI would probably be clunky.  It didn't seem like a good fit for how the tool currently works.  Maybe a button that opens a new import/export window would help.

**Comment by mctrivia** [comment]
yes but I wanted to keep simplest possible and be secure.  This way each card is also useless for forceible future when using 24 word seeds.  80 bits is a lot to brute force.  Did a quick test and using 1 computer could try 2000 combinations per second.  Thats 19,167,393,131,891 years to brute force.  Could chop 7 digits off with an ASIC probably.  May be doable in a life time with several shipping crates full of custom ASICs.

**Comment by iancoleman** [comment]
Thanks for this. I appreciate the consideration and effort that went into this. It's an elegant implementation, especially the ux is seamless.

One consideration is some wallets use 12 word seeds (eg mycelium with 500K installs). This greatly reduces the number of guesses needed. (I usually base my worst-case estimates on zxcvbn which uses 10B guesses per second, see [this zxcvbn demo](https://lowe.github.io/tryzxcvbn/)). The default strength for the tool is 15. Most hardware wallets use 24 words, but I'm cautious about the security of users that don't use 24 word mnemonics.

The question is, should this feature be included (with the addition of a warning when the user enters a weak mnemonic) or should it be kept as a separate tool (eg shamir39, ssss via command line, manual splitting, external web tool)...? I think it's good to keep the feature here but need some time to think through the security a bit more and get more feedback.

Thanks again for putting the thought and time into this feature.

**Comment by mctrivia** [comment]
will add warning showing estimated crack time based on 10billion per second.  18words takes more then 3 years.  probably shouldn't be done with less

**Comment by mctrivia** [comment]
not sure if there is a way to merge pull requests bit 280 shows the time it takes to hack.  18 words and up is probably realistically safe(10billion is a lot when you also have to calculate derivative path and check if address was ever used on a coin they may have).  24 words for sure is safe.

**Comment by iancoleman** [comment]
I personally would not use this feature so merging it comes with some internal conflict, but it's been shown to be secure and people would / will find it useful so let's merge it. Thanks for the effort and commentary in this PR, I appreciate it.

**Comment by joostjager** [comment]
Does picking the words to blank out randomly add any security over splitting in three groups (1-8, 9-16, 17-23) and making cards with two of those groups on it? Which of the two groups are on the card can be encoded more compact, but maybe this explicit format leaves less room for misinterpretation?

**Comment by mctrivia** [comment]
You are correct.  The random was written for psychological reasons.  I have
made this in pdf form also that is just as secure in the manner you
describe.

**Comment by iancoleman** [comment]
@mctrivia, I'm considering some changes and am hoping for your comments

* Add a link to this video outlining the caution required when splitting: https://www.youtube.com/watch?v=p5nSibpfHYE

* Hide the split info by default (mainly because the simple action of 'click generate, see output' shows a warning text on the splits which to me seems kinda silly to be showing warnings from the 'main default use case'.

Any thoughts?

**Comment by mctrivia** [comment]
i think the warning is not needed for 24 word phrases.  But if you want to hide by default that's fine.  Just an extra feature that is really only a good idea with long phrases.

**Pull request merged**
