### PR TITLE
Enable segwit for MONKEY, BCA, BTX, MONA, SYS, VIA, DOGEt, LTCt

### PR DESCRIPTION
**Pull request by PavlosTze**

### CODE REVIEW

**Comment by sidhujag** [comment]
Syscoin is incorrect the signed message is wrong, please refer to #358 for Syscoin

**Comment by PavlosTze** [comment]
Fixed.

**Comment by sidhujag** [comment]
How did you get that bip32 network bytes? Just set it back to what bitcoin uses and the rest is fine.

**Comment by sidhujag** [comment]
Ack

**Comment by iancoleman** [comment]
Thanks for the ping, sorry that I've been very busy. This is still sitting in my todo list, I will get to it but unfortunately can't say when. I appreciate the effort put into the PR.

**Pull request merged**
