### PR TITLE
Add Argoneum (v1.4.1 or above)

### PR DESCRIPTION
**Pull request by osnwt**
Add Argoneum coin (www.argoneum.net) using registered BIP-0044 coin type.

### CODE REVIEW

**Comment by iancoleman** [comment]
No [FAQ info](https://argoneum.net/homepage#faq), no [forum posts](https://argoneum.net/infusions/forum/index.php), why should I merge this if nobody is using it?

**Comment by osnwt** [comment]
I can not speak for the owner of the project, when and how he updates his new site. I am a contractor who does his job well.

Argoneum is backed by a real company registered in the Czech Republic (EU). Argoneum support was recently merged into [NBitcoin library](https://github.com/MetacoSA/NBitcoin/tree/master/NBitcoin.Altcoins) as a basis to support it by one of most popular payment servers, BTCPayServer of the same author (all code is ready and tested, remaining PRs are also submitted). This server uses xpub-based HD chain calculations to generate addresses on behalf of store owners. This tool is a real help for this. Having added support to it, I tried to do my best and provide all the patches for each associated repository, including several for BTCPayServer libraries, server and additional tools (NBXplorer, config generators, etc).

Maybe you think that a lot of such coins as [PutinCoin](https://putincoin.org/) with [$2 daily volume](https://coinmarketcap.com/currencies/putincoin/),  which have neither real contacts, nor real companies, but included in this tool, deserve to be here, and AGM isn't. But I just did the right thing, supporting it everywhere, including this tool.

Maybe the project owner tells something (it's not me). I will neither insist nor argue about this PR.

**Comment by iancoleman** [comment]
Thanks, I appreciate the clarifications! I'll do some more looking but there's nothing wrong with the pr itself, just want to be careful to merge something that's correct and doesn't cause later confusion - easier to check now than correct a mistake later. Thanks again.

**Comment by AGMadmin** [comment]
Hello,
I am founder of Argoneum project. And I would like to please to add Argoneum coin.
We are active project with real base company in Czech Republic (Argoneum s.r.o.).
And currently we are starting to release our first services and this step is important for us.
We have active team with 6+ members

Thank you for understanding and help
Martin Rathouz

**Pull request merged**
