### PR TITLE
Add support for Ripple

### PR DESCRIPTION
**Pull request by amougel**
Add support for Ripple

The private key is displayed without prefix
(prefix is 0x00 for Ripple)

### CODE REVIEW

**Comment by iancoleman** [comment]
Thanks for this.

Can you please add a test for ripple as per [this litecoin example](https://github.com/iancoleman/bip39/blob/6c0227f552c6b09ec13ad771158740432ec0114d/tests.js#L304-L332).
* change [the expected address](https://github.com/iancoleman/bip39/blob/6c0227f552c6b09ec13ad771158740432ec0114d/tests.js#L308) to the correct ripple address
* change [the network being selected](https://github.com/iancoleman/bip39/blob/6c0227f552c6b09ec13ad771158740432ec0114d/tests.js#L314) to the ripple network

Also do you know of any ripple web wallets that support bip39 or bip32 so I can do a third-party verification?

**Comment by amougel** [comment]
Test is passing

**Comment by iancoleman** [comment]
Thanks for this.

A question about the encoding of the private key in [ripple-util.js : convertRipplePriv](https://github.com/LedgerHQ/bip39/blob/64a7d2aad49ddbbcd2eabea8f98f7ff468ca7ccb/src/js/ripple-util.js)

It displays the private key as hex encoded, whereas most private keys (eg bitcoin network) are WIF encoded. Also most ripple sites I've looked at (eg http://ripplepaperwallet.com/) use a Secret Key which is not hex encoded; it looks like it's WIF format `shZ6nh6Wsiwui52TwoL1ZdZ5gYF9E`, presumably base58.

I don't know enough about ripple, but is there a way to present the ripple private key in the table as WIF rather than hex format?

My end goal is to be able to import the private key value from this tool into gatehub.net, then check the address in gatehub matches the address given in this tool. I can't import the hex private key from this tool into gatehub.net.

Is there a way to encode the private key in a format that can be imported into gatehub?

Thanks again for the effort adding ripple to this tool.

**Comment by amougel** [comment]
In  [ http://ripplepaperwallet.com](http://ripplepaperwallet.com) or [gatehub](http://ripplepaperwallet.net), they use a "Secret" and not a private key to recover accounts. You can easily derive a private key from a secret using [deriveKeypair](https://github.com/ripple/ripple-keypairs/blob/master/src/index.js) but not the contrary.

So, it would be possible to represent the private key in WIF format but no platform uses it yet, so I sticked with Hex which is the format supported for signing transaction by the [ripple-lib](https://github.com/ripple/ripple-lib/blob/develop/src/transaction/sign.js)

**Comment by iancoleman** [comment]
Thanks for clarifying the use of hex private key. I wasn't aware of the difference between Secret and Private Key in ripple. Seems like hex is the best format.

**Comment by thinkloop** [comment]
Is there a way to send ripple using the hex key? The [minimalist ripple client](https://jatchili.github.io/minimalist-ripple-client/) requires a secret. I generated an address and sent some ripple to it and not sure how to send it out now.

**Comment by iancoleman** [comment]
I don't know about sending ripple using the hex key. Try asking on the ripple support / forums etc.

Also see https://github.com/iancoleman/bip39/pull/70#issuecomment-306123619 - this tool cannot generate the ripple secret (to my knowledge, any ripple expert who knows otherwise please chime in).

> In http://ripplepaperwallet.com or gatehub, they use a "Secret" and not a private key to recover accounts. You can easily derive a private key from a secret using deriveKeypair but not the contrary.

> So, it would be possible to represent the private key in WIF format but no platform uses it yet, so I sticked with Hex which is the format supported for signing transaction by the ripple-lib

**Comment by thinkloop** [comment]
I've asked around forums without much luck. If a secret is the way to send, and a private key can be derived from it, shouldn't this PR be generating secrets?

**Comment by thinkloop** [comment]
@amougel

**Comment by iancoleman** [comment]
Sure we 'should', but I have no idea how ripple secrets are generated, encoded, decoded or utilised for creating keys and addresses. It seems significantly different to the way bitcoin and bitcoin-based-coins work, so if any ripple expert can chime in (as has been requested many times already in this topic) that would be great. I'm beginning to think maybe this particular tool simply isn't the right one for ripple.

**Comment by btcrobotechxrp** [comment]
I too sent a small amount of XRP into an address and cannot retrieve it because I only have the hex private key.

**Comment by btcrobotechxrp** [comment]
I generated XRP addresses using iancoleman.io and then sent XRP in there. I was eventually able to extract the XRP using on the hex private keys (rather than the "secret keys"). The two threads below should explain it:
https://www.reddit.com/r/Ripple/comments/7r47b3/storing_xrp_in_iancolemanio/
https://www.reddit.com/r/Ripple/comments/7linx0/converting_ripple_private_key/

**Comment by mavigro** [comment]
made the same mistake in importing the hex privkey into a wallet that accepted the key while displaying the corresponding public address but cannot send. I've reviewed the two 4yr old posts above hopeful the rippleterm solution would work but that's offline on the main network so I posted to the first reddit listed above and also xrp chat but if there's been any developments since here on github on how to sign xrp with the hex key I'd great appreciate any addtl. insight. thx

**Pull request merged**
