### PR TITLE
Added support for Safecoin (SAFE)

### PR DESCRIPTION
**Pull request by EternityTula**
Add Safecoin (SAFE) safecoin.org

### CODE REVIEW

**Comment by iancoleman** [comment]
Out of curiosity do you know what SLIP0044 coin 6688 is? It's got the same symbol SAFE and was allocated 10 months ago vs 2 days ago for 19165. Any chance of a conflict / confusion / security issue?

**Comment by EternityTula** [comment]
That is this Safe here: https://coinlib.io/coin/SAFE2/SAFE2
We existed 10 months ago as well.
Most refer to it as "SAFE2"
There are no conflicts, and no security issues.
They are a Dash fork from China, we are a Komodo fork from Canada.

**Comment by iancoleman** [comment]
Thanks for the clarification. SAFE seems like a pretty congested ticker name but so be it!

**Comment by iancoleman** [comment]
The test is failing. Where did the address come from? Using mnemonic `abandon abandon ability` in BIP44 tab gives address `RtxHpnhJz6RY8k9owP3ua5QWraunmewB1G` but the test says it should be `RmV56kPW7jeCmDA8sukHwbR7RZSbg9NFNF` - can you please let me know how the `RmV56...` address was generated?

**Comment by EternityTula** [comment]
Most likely I was mistaken at some stage.
You are absolutely right -  mnemonic `abandon abandon ability` in BIP44 should give `RtxHpnhJz6RY8k9owP3ua5QWraunmewB1G` 
Thank you very much!

**Pull request merged**
