### PR TITLE
Updated Zcoin (XZC) Due to its rebrand fo Firo (FIRO)

### PR DESCRIPTION
**Pull request by r1979**
https://zcoin.io/zcoin-is-becoming-firo/

### CODE REVIEW

**Comment by r1979** [comment]
Only the coin name and the ticker are changing.

**Comment by iancoleman** [comment]
Rather than removing zcoin, is it worth keeping Zcoin for legacy reasons and changing the displayed name to `Zcoin (now renamed Firo)`?

**Comment by r1979** [comment]
Good point. Although I would prioritize the present state of things upon legacy and opt for `Firo (Zcoin rebrand)` (or something similar). What do you think?

**Comment by iancoleman** [comment]
I think we can do both. Let's name them

* Firo (Zcoin rebrand)
* Zcoin (rebranded to Firo)

I'll merge this and update the names myself. Thanks for the PR and feedback!

**Comment by iancoleman** [comment]
See https://github.com/iancoleman/bip39/commit/38626a2d1fd10cac1dd3da971ef5057a2a1dc06b

**Pull request merged**
