### PR TITLE
Added Bitcoin Green

### PR DESCRIPTION
**Pull request by skironDotNet**
tested priv and pub key

### CODE REVIEW

**Comment by iancoleman** [comment]
Thanks for this.

The addition of BITG is great, thanks for that.

The change to `-m SimpleHTTPServer is a python2 vs python3 thing. Python 3 on windows would also be `-m http.server`. This is not a 'windows' difference, so the change to readme is not valid for merging.

The version is only changed when a release is made, and this PR is not a release, so the commit changing the version is not something I'd want to merge.

Please remove the changes to readme and the version, keeping just the BITG parameters.

**Comment by skironDotNet** [comment]
You have clean BITG in same repo now.

Re: "This is not a 'windows' difference", the only reason I want to add it is because I don't have a module like you have in readme and I always have to research for "correct" module name

**Comment by skironDotNet** [comment]
Do you want me to create a new pull request?

**Comment by iancoleman** [comment]
> the only reason I want to add it is because I don't have a module like you have in readme and I always have to research for "correct" module name

Fair enough, I think it's a good idea, I can add a note about python2 using a different command for the server. Thanks for the feedback and pull request.

**Pull request merged**
